bomach/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')), # The CKEditor path
    path('summernote/', include('django_summernote.urls')),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/urls.py
from django.urls import path
from django.views.generic.base import TemplateView
from .import views

app_name = 'main'

urlpatterns = [
    path('', views.Index.as_view(), name='home'),
    path('index', views.Index.as_view(), name='index'),
    path('about', views.About.as_view(), name='about'),
    path('services', views.Service.as_view(), name='services'),
    path('email-subscribe', views.EmailSubscribe.as_view(), name='email-subscribe'),
    path('services/<slug:slug>', views.ServiceDetail.as_view(), name='service-details'),
    path('get-sub-service', views.GetSubService.as_view(), name='get-sub-service'),
    path('available-datetime', views.AvailableDatetime.as_view(), name='available-datetime'),
    path('contact', views.Contact.as_view(), name='contact'),
    path('booking', views.Booking.as_view(), name='booking'),
    path('team', views.Team.as_view(), name='team'),
    # path('product', views.Products.as_view(), name='product'),
    # path('product/<slug:slug>', views.ProductDetail.as_view(), name='product-details'),
    path('blog', views.Blogs.as_view(), name='blog'),
    path('blog/<slug:slug>', views.BlogDetail.as_view(), name='blog-details'),
    path('project', views.Projects.as_view(), name='project'),
    path('project/<slug:slug>', views.ProjectDetail.as_view(), name='project-details'),

]

main/models.py
from django.db import models
from django.utils import timezone
from django.utils.text import slugify
from django.db.models.signals import post_save, pre_save
from django.core.validators import MinValueValidator, MaxValueValidator
from django_summernote.fields import SummernoteTextField
import bleach
from .utils import (
    send_email_quote, send_email_contact, send_booking_email, send_user_booking_email, unique_id)

# Create your models here.

STAFF_EMAILS = ['benantoto@gmail.com', 'admin@yuhga.org', 'bomachgroupmanagement@gmail.com']

class ImageUrl:
    def image_url(self):
        if self.image:
            return self.image.url

        # this has the potential to fail when i use cloudinary to host static files
        return '/static/assets/img/logo/yuhga.png'


class CustomBaseModel:
    def short_content(self):
        if self.content:
            rich_text = self.content.replace('&nbsp;', '')
            text = bleach.clean(rich_text, tags=[], strip=True)
            cleaned_string = ' '.join(list(text.split()))
            return f"{cleaned_string[:50]}.."
        return ''

    def save(self, *args, **kwargs):
        self.content = self.content.replace('&lt;o:p&gt;&lt;/o:p&gt;', '')
        super().save(*args, **kwargs)


class Service(CustomBaseModel, models.Model, ImageUrl):
    name = models.CharField(max_length=250, unique=True)
    slug = models.CharField(max_length=250, unique=True, blank=True)
    image = models.ImageField(upload_to='images/')
    content = SummernoteTextField()
    rating = models.IntegerField(
        validators=[
            MinValueValidator(0, message='Value cannot be less than 0.'),
            MaxValueValidator(100, message='Value cannot be greater than 100.')
        ],
        default=80) # ranting over 100%
    priority = models.IntegerField(default=0)
    date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name


class SubService(CustomBaseModel, models.Model, ImageUrl):
    name = models.CharField(max_length=250, unique=True)
    service = models.ForeignKey(Service, on_delete=models.CASCADE, null=True)
    slug = models.CharField(max_length=250, unique=True, blank=True)
    image = models.ImageField(upload_to='images/')
    content = SummernoteTextField()
    rating = models.IntegerField(
        validators=[
            MinValueValidator(0, message='Value cannot be less than 0.'),
            MaxValueValidator(100, message='Value cannot be greater than 100.')
        ],
        default=80) # ranting over 100%
    priority = models.IntegerField(default=0)
    date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name


class Project(CustomBaseModel, models.Model, ImageUrl):
    name = models.CharField(max_length=250, null=True, blank=True)
    slug = models.CharField(max_length=250, unique=True, blank=True)
    sub_service = models.ForeignKey(SubService, on_delete=models.CASCADE, null=True, blank=True)
    image = models.ImageField(upload_to='images/', blank=True, null=True)
    content = SummernoteTextField(blank=True, null=True)
    priority = models.IntegerField(default=0)
    date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name


class ProductImage(models.Model, ImageUrl):
    name = models.CharField(max_length=250, default='N/A')
    priority = models.IntegerField(default=0)
    image = models.ImageField(upload_to='images/')
    date = models.DateTimeField(default=timezone.now)


def product_id():
    return unique_id(Product)

class Product(CustomBaseModel, models.Model):
    id = models.CharField(primary_key=True, max_length=6, default=product_id)
    name = models.CharField(max_length=250)
    slug = models.CharField(max_length=250, unique=True, blank=True)
    content = SummernoteTextField()
    service = models.ForeignKey(Service, on_delete=models.CASCADE, null=True, blank=True)
    video = models.URLField(max_length=500, null=True)
    product_images = models.ManyToManyField(ProductImage)
    priority = models.IntegerField(default=0)
    date = models.DateTimeField(default=timezone.now)

    def video_url(self):
        if self.video:
            return (
                f"https://www.youtube.com/embed/{self.video.split('/')[-1].split('v=')[-1].split('&')[0].split('?')[0]}?rel=0"
            )
        return ''

    def image_url(self):
        """
            Gets the first product image NOTE they can be more that one product image
        """
        product_image = self.product_images.order_by('-priority').first()
        if product_image:
            return product_image.image_url()
        return '/static/assets/img/logo/yuhga.png'

    def __str__(self):
        return self.name


class Blog(CustomBaseModel, models.Model, ImageUrl):
    title = models.CharField(max_length=250, null=True, blank=True)
    author = models.CharField(max_length=250, null=True, blank=True)
    slug = models.CharField(max_length=250, unique=True, blank=True)
    image = models.ImageField(upload_to='images/', blank=True, null=True)
    content = SummernoteTextField(blank=True, null=True)
    priority = models.IntegerField(default=0)
    date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title


class HomeSlider(models.Model, ImageUrl):
    # title = models.CharField(max_length=500)
    big_text = models.CharField(max_length=500)
    small_text = models.CharField(max_length=500)
    image = models.ImageField(upload_to='images/')
    priority = models.IntegerField(default=0)
    date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.big_text


class CustomerReview(models.Model):
    name = models.CharField(max_length=250)
    review = models.CharField(max_length=2000)
    occupation = models.CharField(max_length=500)
    priority = models.IntegerField(default=0)
    date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name


class Employee(models.Model, ImageUrl):
    name = models.CharField(max_length=250)
    job_title = models.CharField(max_length=250)
    facebook = models.CharField(max_length=200, null=True, blank=True)
    twitter = models.CharField(max_length=200, null=True, blank=True)
    instagram = models.CharField(max_length=200, null=True, blank=True)
    image = models.ImageField(upload_to='images/')
    priority = models.IntegerField(default=0)
    date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name


class PartnerSlider(models.Model, ImageUrl):
    company = models.CharField(max_length=250, default="N/A")
    image = models.ImageField(upload_to='images/')
    priority = models.IntegerField(default=0)
    date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.company


class Quote(models.Model):
    name = models.CharField(max_length=250, default="N/A")
    phone = models.CharField(max_length=250, default="N/A")
    email = models.CharField(max_length=250, default="N/A")
    message = models.CharField(max_length=10000, default="N/A")
    location = models.CharField(max_length=1000, default="N/A")
    service = models.ForeignKey(Service, on_delete=models.CASCADE, blank=True, null=True)
    sub_service = models.ForeignKey(SubService, on_delete=models.CASCADE, blank=True, null=True)
    date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Service Quote' 
        verbose_name_plural = 'Service Quote'


class ContactUs(models.Model):
    name = models.CharField(max_length=250, default="N/A")
    phone = models.CharField(max_length=250, default="N/A")
    email = models.CharField(max_length=250, default="N/A")
    message = models.CharField(max_length=10000, default="N/A")
    location = models.CharField(max_length=1000, default="N/A")
    date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Contact us' 
        verbose_name_plural = 'Contact us'


class Booking(models.Model):
    BRANCH_CHOICES = [
        ('Enugu Branch', 'Enugu Branch'),
        ('Port Harcourt Branch', 'Port Harcourt Branch'),
    ]
    name = models.CharField(max_length=250)
    phone = models.CharField(max_length=250)
    email = models.CharField(max_length=250)
    message = models.CharField(max_length=10000)
    location = models.CharField(max_length=1000, choices=BRANCH_CHOICES, default='Enugu Branch')
    service = models.ForeignKey(Service, on_delete=models.CASCADE, blank=True, null=True)
    sub_service = models.ForeignKey(SubService, on_delete=models.CASCADE, blank=True, null=True)
    meeting_time = models.DateTimeField()
    duration_in_minutes = models.IntegerField(default=30)
    date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Booking' 
        verbose_name_plural = 'Booking'


class Email(models.Model):
    email = models.EmailField(unique=True, null=False)
    is_active = models.BooleanField(default=True)
    date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.email

    class Meta:
        verbose_name = 'Email Subscriber' 
        verbose_name_plural = 'Email Subscribers'
    


# django signal
def create_slug(sender, instance, *args, **kwargs):
    instance.slug = slugify(instance.name)

def create_slug_title(sender, instance, *args, **kwargs):
    instance.slug = slugify(instance.title)

def send_quote_email_signal(sender, instance, *args, **kwargs):
    send_email_quote(STAFF_EMAILS, instance)

def send_contact_email_signal(sender, instance, *args, **kwargs):
    send_email_contact(STAFF_EMAILS, instance)

def send_booking_email_signal(sender, instance, *args, **kwargs):
    send_booking_email(STAFF_EMAILS, instance)

main/forms.py
from django import forms
from .models import Quote, Service, SubService, ContactUs, Booking, Email


class EmailForm(forms.ModelForm):
    email = forms.EmailField(required=False, label='', max_length=1000,  widget=forms.EmailInput(attrs={
        'placeholder':'Email Address', 'class': 'form-control', 'id': 'emailAddress'
        }))

    class Meta:
        model = Email
        fields = ['email']


class QuoteForm(forms.ModelForm):
    name = forms.CharField(required=True, label='', max_length=500,  widget=forms.TextInput(attrs={
        'placeholder':'Full Name', 'id': 'name'
        }))
    phone = forms.CharField(required=True, label='', max_length=500,  widget=forms.TextInput(attrs={
        'placeholder':'Phone', 'id': 'phone'
        }))
    email = forms.EmailField(required=True, label='', max_length=500,  widget=forms.EmailInput(attrs={
        'placeholder':'Email', 'id': 'email'
        }))
    message = forms.CharField(required=True, label='', max_length=10000, widget=forms.Textarea(attrs={
        'placeholder':'Message', 'id': 'message'
        }))

    phone = forms.CharField(required=True, label='', max_length=500,  widget=forms.TextInput(attrs={
        'placeholder':'Phone', 'id': 'phone'
        }))

    location = forms.CharField(required=True, label='', max_length=1000, widget=forms.TextInput(attrs={
        'placeholder':'Location', 'id': 'location'
        }))

    service = forms.ModelChoiceField(required=True, label='Service', queryset=Service.objects.all().order_by('-priority'),
     initial=Service.objects.order_by('-priority').first())

    sub_service = forms.ModelChoiceField(required=False, label='Service', 
        queryset=SubService.objects.all().order_by('-priority'), 
        initial=SubService.objects.filter(
            service=Service.objects.order_by('-priority').first().pk).order_by('-priority').first()
        )
    
    class Meta:
        model = Quote
        fields = ['name', 'phone', 'email', 'service', 'sub_service', 'location', 'message']


class ContactForm(forms.ModelForm):
    name = forms.CharField(required=True, label='', max_length=500,  widget=forms.TextInput(attrs={
        'placeholder':'Full Name', 'id': 'name'
        }))
    phone = forms.CharField(required=True, label='', max_length=500,  widget=forms.TextInput(attrs={
        'placeholder':'Phone', 'id': 'phone'
        }))
    email = forms.EmailField(required=True, label='', max_length=500,  widget=forms.EmailInput(attrs={
        'placeholder':'Email', 'id': 'email'
        }))
    message = forms.CharField(required=True, label='', max_length=10000, widget=forms.Textarea(attrs={
        'placeholder':'Message', 'id': 'message'
        }))

    location = forms.CharField(required=True, label='', max_length=1000, widget=forms.TextInput(attrs={
        'placeholder':'Location', 'id': 'location'
        }))

    class Meta:
        model = ContactUs
        fields = ['name', 'phone', 'email', 'location', 'message']


class BookingForm(forms.ModelForm):
    name = forms.CharField(required=True, label='', max_length=500,  widget=forms.TextInput(attrs={
        'placeholder':'Full Name', 'id': 'name'
        }))
    phone = forms.CharField(required=True, label='', max_length=500,  widget=forms.TextInput(attrs={
        'placeholder':'Phone', 'id': 'phone'
        }))
    email = forms.EmailField(required=True, label='', max_length=500,  widget=forms.EmailInput(attrs={
        'placeholder':'Email', 'id': 'email'
        }))
    message = forms.CharField(required=True, label='', max_length=10000, widget=forms.Textarea(attrs={
        'placeholder':'Reason', 'id': 'message'
        }))

    location = forms.ChoiceField(choices=Booking.BRANCH_CHOICES, initial='Enugu Branch')

    service = forms.ModelChoiceField(required=True, label='Service', queryset=Service.objects.all().order_by('-priority'),
     initial=Service.objects.order_by('-priority').first())

    sub_service = forms.ModelChoiceField(required=False, label='Service', 
        queryset=SubService.objects.all().order_by('-priority'), 
        initial=SubService.objects.filter(
            service=Service.objects.order_by('-priority').first().pk).order_by('-priority').first()
        )
    
    meeting_time = forms.DateTimeField(required=True, label='', widget=forms.DateTimeInput(attrs={
        'placeholder':'Meeting time', 'id': 'meeting_time', 'type': 'datetime-local'
        })) 

    class Meta:
        model = Booking
        fields = ['name', 'phone', 'email', 'service', 'sub_service', 'location', 'message', 'meeting_time']

templates/main/blog-details.html
{% load static %}

<!doctype html>
<html class="no-js" lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Blog detail - yuhga</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% include "./include/head.html" %}

</head>

<body>
{% include "./include/header_others.html" %}

<!--    Page title area start here-->
<div class="page-title-area pt-70 pb-70" data-background="{% static 'assets/img/bomach/new/Bomach-Engineering.jpg' %}">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div class="page-title-wrapper text-center">
                    <h1 class="page-title">{{ blog.title }}</h1>
                    <div class="breadcrumb breadcrumb-list">
                        <nav aria-label="Breadcrumbs" class="breadcrumb-trail breadcrumbs">
                            <ul class="trail-items">
                                <li  class="trail-item trail-begin">
                                    <a href="/blog"><span >Blog</span></a>  
                                </li>
                                <li class="trail-item trail-end"><span>Blog Details</span></li>
                            </ul>
                        </nav>                            
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!--   Page title area end here-->

<!-- Blog area start here-->
<div class="blog-area pt-120 pb-80">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 blog-post-items blog-padding">
                <div class="blog__wrapper mr-50">
                    <article id="post-79" class="blog__item-2 mb-70 format-image mb-50 post-79 post">
                        <div class="blog__thumb-2 m-img">
                        <img src="{{ blog.image_url }}" alt="img">
                        </div>
                        <div class="blog__content-2">
                            <div class="post-meta mb-20">
                                <span><i class="far fa-calendar-check"></i> {{blog.date|date:'F j, Y' }} </span>
                                <span><i class="far fa-user"></i>{{ blog.author }}</span>
                                <!-- <span><a href="blog-details"><i class="far fa-comments"></i> No Comments</a></span> -->
                            </div>
                            <h3>{{ blog.title }}</h3>
                            <div class="active-like-link mb-30">
                                <p>{{ blog.content|safe }}</p>
                             </div>
                        </div>
                    </article>	
                </div>
            </div>
            <div class="col-lg-4">
                <div class="blog__sidebar">
                    <div id="bdevs-latest-posts-2" class="sidebar__widget mb-50 widget_bdevs-latest-posts">
                        <h4 class="sidebar__widget-title mb-50">
                            Recent News
                        </h4>     	
                        <div class="sidebar__widget-content">
                            <div class="rc-post"> 
                                {% for i in blogs %}  	
                                <div class="d-flex mb-20">
                                    <div class="rc-thumb mr-15">
                                        <a href="/blog/{{ i.slug }}"><div class="sidebar-posts-bg-thumb" data-background="{{ i.image_url }}"></div></a>
                                    </div>
                                    <div class="rc-text">
                                        <h6><a href="/blog/{{ i.slug }}">{{ i.title }}</a></h6>
                                        <div class="rc-meta">{{ i.date|date:'F j, Y' }} </div>
                                    </div>
                                </div>
                                {% endfor %}
                            </div> 
                        </div> 
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Blog area end here-->

{% include "./include/footer.html" %}
{% include "./include/foot.html" %}

</body>
</html>

templates/main/booking.html
{% load static %}

<!doctype html>
<html class="no-js" lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Book us - yuhga</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% include "./include/head.html" %}

</head>

<body>
{% include "./include/header_others.html" %}

<!-- page title area start here-->
<div class="page-title-area pt-70 pb-70" data-background="{% static 'assets/img/bomach/new/Bomach-Engineering.jpg' %}">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div class="page-title-wrapper text-center">
                    <h1 class="page-title">Book us</h1>
                    <div class="breadcrumb breadcrumb-list">
                        <nav aria-label="Breadcrumbs" class="breadcrumb-trail breadcrumbs">
                            <ul class="trail-items">
                                <li  class="trail-item trail-begin">
                                    <a href="/"><span >Home</span></a>  
                                </li>
                                <li class="trail-item trail-end"><span>Contact us</span></li>
                            </ul>
                        </nav>                            
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- page title area end here-->

<!-- contact area start here -->
<section class="tp-contact-area pb-120">
    <div class="container">
        <div class="row">
            <div class="col-lg-10">
                <div class="section_title_wrapper mb-50 wow fadeInUp" data-wow-delay="0.3s" style="visibility: visible; animation-delay: 0.3s; animation-name: fadeInUp;">
                    <span class="subtitle service-ex-subtitle">
                        Contact us
                    </span>                       
                    <h2 class="msection-title mb-35">
                        If you Have Any Query, Book an <span>Appointment</span>  with us 
                    </h2>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-4">
                <div class="row custom-mar-20">
                    <div class="col-lg-12 col-md-4 col-sm-6 custom-pad-20">
                        <div class="tp-contact-info mb-40 wow fadeInUp" data-wow-delay=".4s">
                            <div class="tp-contact-info-icon">
                                <i class="flaticon-location"></i>
                            </div>
                            <div class="tp-contact-info-text">
                                <h4 class="tp-contact-info-title mb-15">Address</h4>
                                <p>Suite 9 Swiss Guard Plaza, 450 Ogui Road <br>Enugu State</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-12 col-md-4 col-sm-6 custom-pad-20">
                        <div class="tp-contact-info mb-40 wow fadeInUp" data-wow-delay=".6s">
                            <div class="tp-contact-info-icon tp-contact-info-icon-phone">
                                <i class="flaticon-phone-call"></i>
                            </div>
                            <div class="tp-contact-info-text">
                                <h4 class="tp-contact-info-title mb-15">Phone</h4>
                                <a href="tel:08036656173">080 3665 6173</a>
                                <a href="tel:09015555159">090 1555 5159</a>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-12 col-md-4 col-sm-6 custom-pad-20">
                        <div class="tp-contact-info mb-40 wow fadeInUp" data-wow-delay=".8s">
                            <div class="tp-contact-info-icon">
                                <i class="flaticon-letter"></i>
                            </div>
                            <div class="tp-contact-info-text">
                                <h4 class="tp-contact-info-title mb-15">Email</h4>
                                <a href="mailto:admin@yuhga.org"><span>admin@yuhga.org</span></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-8">
                <form action="{{ request.path }}" method="POST">
                    {% csrf_token %}
                    <div class="tp-contact-form wow fadeInUp" data-wow-delay=".6s">
                <div class="row custom-mar-20">
                    <div class="col-md-6 custom-pad-20">
                        <div class="tp-contact-form-field mb-20">
                            {{ form.name }}
                        </div>
                    </div>
                    <div class="col-md-6 custom-pad-20">
                        <div class="tp-contact-form-field mb-20">
                            {{ form.email }}
                        </div>
                    </div>
                    <div class="col-md-6 custom-pad-20">
                        <div class="tp-contact-form-field mb-20">
                            {{ form.phone }}
                        </div>
                    </div>
                    <div class="col-md-6 custom-pad-20 mb-20">
                        <div class="tp-contact-form-field select-field-arrow">
                            {{ form.location }}
                        </div>
                    </div>
                    <div class="col-md-6 custom-pad-20 mb-20">
                        <div class="tp-contact-form-field select-field-arrow">
                            {{ form.service }}
                        </div>
                    </div>
                    <div class="col-md-6 custom-pad-20 mb-20">
                        <div class="tp-contact-form-field select-field-arrow">
                            {{ form.sub_service }}
                        </div>
                    </div>

                    <div class="col-md-12 custom-pad-20">
                        <div class="tp-contact-form-field mb-20">
                            {{ form.message }}
                        </div>
                    </div>
                    <div class="col-md-12 custom-pad-20">
                        <div class="tp-contact-form-field mb-20">
                            {{ form.meeting_time }}
                        <span id="date_msg" class="text-danger" style="display: none;"></span>
                        </div>
                    </div>
                    <div class="col-md-12 custom-pad-20">
                        <div class="tp-contact-form-field">
                            <button type="submit" class="theme-btn home2-btn btn-before"><i class="fal fa-angle-double-right"></i> Book appointment</button>
                        </div>
                    </div>
                </div>
            </div>
                </form>
            </div>
        </div>
    </div>
</section>
<!-- contact area end here -->

{% include "./include/footer.html" %}
{% include "./include/foot.html" %}

<script>
    $(document).ready(function() {
    $('#id_service').change(function() {
        var service_id = $(this).val();

        // Get the CSRF token value
        var csrftoken = $("[name=csrfmiddlewaretoken]").val();

        $.ajax({
            url: '/get-sub-service',
            type: 'POST',
            data: {
                'service_id': service_id,
                'csrfmiddlewaretoken': csrftoken
            },
            success: function(data) {
                var childField = $('#id_sub_service');
                childField.empty();

                for (var i = 0; i < data.length; i++) {
                    var option = $('<option selected>').val(data[i].id).text(data[i].name);
                    if (i != 0){
                        // option.attr('selected', '');
                        option.removeAttr('selected')
                    }
                    childField.append(option);
                }

                var niceSelect = $('.nice-select:eq(3)');

                ul = niceSelect.children('.list').children();
                niceSelect.children('.current').text('')

                for (i=0; i < ul.length; i++){
                    ul.eq(i).remove()
                }

                try {
                    niceSelect.children('.current').text(data[0].name)
                    niceSelect.children('.list')

                    for (var i = 0; i < data.length; i++) {
                        var li = $('<li>').text(data[i].name);
                        li.addClass('option');
                        li.attr('data-value', `${data[i].id}`);
                        if (i == 0){
                            li.addClass('selected');
                        }
                        niceSelect.children('.list').append(li);
                    }
                    
                }catch (e){
                    console.log('empty data')
                }

                // <li data-value="1" class="option selected">ihjsdhjdsjkd</li>
            }
        });
    });
});

</script>   

<script>

var validOptions = [
    {% for item in valid_options %}
      "{{ item }}"{% if not forloop.last %}, {% endif %}
    {% endfor %}
  ];

niceSelectUl = $('.nice-select:eq(3)').children('.list').children();

niceSelectUl.each(function() {
  var liText = $(this).text().trim();
  // Check if the <li> text is not in the validOptions
  if (validOptions.indexOf(liText) === -1) {
    $(this).remove(); // Remove the unmatched <li> element
  }
});
</script>

<script>
    $(document).ready(function() {
    // Get the datetime field element
    var datetimeField = $('#meeting_time');
    var date_msg = $('#date_msg');

    datetimeField.on('change', function() {
    var datetimeValue = datetimeField.val();
    var csrftoken = $("[name=csrfmiddlewaretoken]").val();

    // Send the datetime value to the Django view using AJAX
    $.ajax({
      url: '/available-datetime',
      method: 'POST',
      data: {
        'meeting_time': datetimeValue,
        'csrfmiddlewaretoken': csrftoken

      },
      success: function(response) {
        if (!response.msg){
            datetimeField.addClass('border');
            datetimeField.addClass('border-danger');
            date_msg.text(response.date_msg);
            date_msg.show()
        }else{
            datetimeField.removeClass('border');
            datetimeField.removeClass('border-danger');
            date_msg.text('');
            date_msg.hide()
        }
      }
    });
  });
});

</script>
</body>

</html>